---
title: 'Forza Horizon 5: Exploratory Dashboard'
author: "Griffin Lester"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  flexdashboard::flex_dashboard:
    orientation: columns 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
pacman::p_load(tidyverse, magrittr, stringr, plotly)

# Read the data
forza = readRDS("Clean_Forza.rds")

# Subset out observations whose price is greater than 5 million credits
cheap = subset(forza, In_Game_Price < 5000000)
```

column {data-width = 300}
-----------------------------------------------------------------

### Explanatory Modeling: Price

```{r model, echo = FALSE, cache = TRUE}
reg = lm(In_Game_Price ~ Stock_Rating + speed + handling + acceleration +
           launch + braking + Offroad + Horse_Power + Weight_lbs,
         data = cheap)
summary(reg)
```

column {data-width = 300}
-----------------------------------------------------------------

### Price vs. Stock Rating

```{r price_v_stock, echo = FALSE, cache = TRUE}
cheap %>% 
  ggplot(aes(x = In_Game_Price, y = Stock_Rating)) +
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ I(x^0.25)) +
  theme_bw() +
  labs(x = "Price", y = "Rating", title = "Price vs. Rating",
       caption = "Blue line = x^0.25 line of fit.") +
  theme(plot.title = element_text(hjust = 0.5))
ggplotly()
```

### Price vs. Horse Power

```{r price_v_hp, echo = FALSE, cache = TRUE}
cheap %>% 
  ggplot(aes(x = In_Game_Price, y = Horse_Power, color = stock_specs)) +
  geom_point() +
  theme_bw() +
  xlim(0, 3000001) +
  labs(x = "Price", y = "Horse Power (HP)", title = "Price vs. Horse Power") +
  theme(plot.title = element_text(hjust = 0.5))
ggplotly()
```




